// Renders the GitHub profile README (repository root) from the same data as
// the site. Pure: takes prepared views, returns markdown.
import type { Research } from '../../src/content/schemas.ts';
import type { ProjectView, ReleaseView } from '../../src/lib/merge.ts';
import type { ContributionsFile, StatsFile } from '../lib/schemas.ts';
import type { LogoRef } from '../../src/lib/logos-map.ts';

const SITE = 'https://matthiaskoenig.github.io';
const ASSETS_ROOT = 'https://raw.githubusercontent.com/matthiaskoenig/matthiaskoenig/develop/site/src/assets';
const ASSETS = `${ASSETS_ROOT}/projects`;
const logoImg = (ref: LogoRef | null | undefined, height: number) => (ref ? `<img src="${ASSETS_ROOT}/${ref.folder}/${ref.file}" height="${height}" alt=""> ` : '');
const IMAGES = './images/generated';

const fmt = (iso: string) => new Date(iso).toLocaleDateString('en-GB', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' });
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function pythonRange(p: ProjectView): string | null {
  const v = p.meta?.pythonVersions ?? [];
  if (v.length > 1) return `Python ${v[0]}–${v[v.length - 1]}`;
  if (v.length === 1) return `Python ${v[0]}`;
  return p.meta?.requiresPython ? `Python ${p.meta.requiresPython}` : null;
}

export interface ReadmeData {
  research: Research[];
  projects: ProjectView[];
  releases: ReleaseView[];
  /** logo per `owner/name`, for the releases list */
  logos: Record<string, LogoRef | null>;
  stats: StatsFile;
  contributions: ContributionsFile;
  fetchedAt: string;
}

export function renderReadme(d: ReadmeData): string {
  const out: string[] = [];
  out.push('<!-- Generated by site/scripts/render-readme.ts from the same data as matthiaskoenig.github.io. Edit the template there, not this file. -->');
  out.push('# Prof. Dr. Matthias König');
  out.push('');
  const topLang = d.stats.languages[0];
  out.push(
    `**${d.stats.repoCount} repositories · ${d.stats.totalStars} stars · ${d.contributions.totals.commits} commits and ${d.contributions.totals.pullRequests} pull requests in the last year**` +
      (topLang ? ` · primary language ${topLang.name} in ${topLang.repos} repositories` : '') +
      ` ([details](${SITE}/#contributions))`,
  );
  out.push('');
  out.push(
    'Research software engineering for systems medicine: open-source tools, standards and reproducible workflows for digital twins of the liver and human physiology. ' +
      'Professor of Metabolic Inflammation and Carcinogenesis of the Liver at the [University of Lübeck](https://www.uksh.de/) (UKSH, Campus Lübeck) and head of the ' +
      '[König Lab](https://livermetabolism.com) at Humboldt-Universität zu Berlin.',
  );
  out.push('');
  out.push(
    `🔗 **[matthiaskoenig.github.io](${SITE})** (this page with interactive charts) · [livermetabolism.com](https://livermetabolism.com) · ` +
      '[ORCID](https://orcid.org/0000-0003-1725-179X) · [CV](https://livermetabolism.com/cv/)',
  );
  out.push('');

  out.push('## 🔬 Research interests');
  out.push('');
  for (const r of [...d.research].sort((a, b) => a.order - b.order)) {
    out.push(`- <img src="${IMAGES}/topics/${r.id}.svg" height="20" alt=""> **[${r.name}](${r.link})** — ${r.description.replace(/\s+/g, ' ').trim()}`);
  }
  out.push('');

  out.push('## 💻 Main projects');
  out.push('');
  out.push('| | Project | Latest release | Language | License | Links |');
  out.push('|---|---|---|---|---|---|');
  for (const p of d.projects) {
    const logo = p.image ? `<img src="${ASSETS}/${p.image}" height="28" alt="">` : '';
    const name = `**[${p.name}](${p.repo.htmlUrl})**<br><sub>${cell(p.title)}</sub>`;
    const rel = p.latestRelease ? `[${p.latestRelease.tag}](${p.latestRelease.htmlUrl})<br><sub>${fmt(p.latestRelease.publishedAt)}</sub>` : '—';
    const lang = [p.repo.language, pythonRange(p)].filter(Boolean).join('<br><sub>') + (pythonRange(p) ? '</sub>' : '');
    const license = p.repo.license ?? p.meta?.license ?? '—';
    const curatedIsZenodo = !!p.doi && p.doi.startsWith('10.5281/zenodo.');
    const zenodo = p.meta?.zenodoDoi ?? (curatedIsZenodo ? p.doi : null);
    const paper = p.doi && !curatedIsZenodo ? p.doi : null;
    const links = [
      p.docs ? `[Docs](${p.docs})` : null,
      p.homepage ? `[Website](${p.homepage})` : null,
      zenodo ? `[Zenodo](https://doi.org/${zenodo})` : null,
      paper ? `[Paper](https://doi.org/${paper})` : null,
    ].filter(Boolean).join(' · ');
    out.push(`| ${logo} | ${name} | ${rel} | ${lang || '—'} | ${license} | ${links} |`);
  }
  out.push('');
  for (const p of d.projects) out.push(`- **${p.name}** — ${p.description.replace(/\s+/g, ' ').trim()}`);
  out.push('');

  out.push('## 📊 Contributions');
  out.push('');
  out.push(`[![Contribution calendar of the last year](${IMAGES}/charts/calendar.svg)](${SITE}/#contributions)`);
  out.push('');
  out.push(`[![Contributions per month](${IMAGES}/charts/contributions.svg)](${SITE}/#contributions)`);
  out.push('');

  out.push('## 🚀 Latest releases');
  out.push('');
  out.push(`[![Release history per repository](${IMAGES}/charts/release-timeline.svg)](${SITE}/#releases)`);
  out.push('');
  out.push(`Latest release of every repository on [the site](${SITE}/#releases) that published one in the last two years:`);
  out.push('');
  for (const r of d.releases) {
    out.push(`- ${logoImg(d.logos[r.repo], 16)}**${r.projectName}** [${r.name}](${r.htmlUrl}) · ${fmt(r.publishedAt)}${r.summary ? ` — ${r.summary}` : ''}`);
  }
  out.push('');

  out.push('## ⭐ Repositories');
  out.push('');
  out.push(`[![Stars per repository](${IMAGES}/charts/stars.svg)](${SITE}/#repositories)`);
  out.push('');
  out.push(`![Primary language](${IMAGES}/charts/stars-legend.svg)`);
  out.push('');
  out.push(`The full catalog with search and sorting, the interactive charts and the zoomable release history are on **[${SITE.replace('https://', '')}](${SITE})**.`);
  out.push('');

  out.push('## 📚 Learn more');
  out.push('');
  out.push(
    'Publications, projects, team and teaching of the König Lab: [livermetabolism.com](https://livermetabolism.com) ' +
      '([publications](https://livermetabolism.com/publications), [projects](https://livermetabolism.com/projects)). ' +
      'Interested in collaborating? Get in touch via the lab website.',
  );
  out.push('');
  out.push('---');
  out.push('');
  out.push(
    `<sub>Generated from GitHub data fetched on ${d.fetchedAt.slice(0, 10)}; refreshed weekly by the <em>Update profile README</em> workflow. ` +
      'This repository also holds the source of the site under <a href="./site">site/</a> (see <a href="./site/README.md">site/README.md</a>).</sub>',
  );
  out.push('');
  return out.join('\n');
}
